apiVersion: apps/v1
kind: Deployment
metadata: 
    name: {{ .Values.db.name }}
spec:
    selector:
        matchLabels:
            tier: {{ .Values.db.name }}
    template:
        metadata:
            name: {{ .Values.db.name }}
            labels:
                tier: {{ .Values.db.name }}
        spec:
            containers:
                - name: {{ .Values.db.name }}
                  image: {{ .Values.image.db }}
                  env:
                    - name: MYSQL_DATABASE
                      valueFrom:
                        secretKeyRef:
                            name: {{ .Values.db.name }}
                            key: name
                    - name: MYSQL_USER
                      valueFrom:
                        secretKeyRef:
                            name: {{ .Values.db.name }}
                            key: user
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: {{ .Values.db.name }}
                            key: password

                        
                  ports:
                    - containerPort: 3306
                      name: sqlflask
                  imagePullPolicy: Always
            volumes:
              - name: mysqlstorage
                persistentVolumeClaim:
                  claimName: dbvol
              

            