apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/tmp/data" 