apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.db.name }}
type: Opaque
data:
    name: {{ .Values.db.name | b64enc}}
    user: {{ .Values.db.user | b64enc}}
    password: {{ .Values.db.password | b64enc}}


